openapi: 3.0.1
info:
  title: cupl Administrator API
  description: API endpoints that require administrator access.
  contact:
    url: www.plotsensor.com
    email: malcolm@plotsensor.com
  version: 0.0.2
tags:
  - name: Tags
    description: Tag endpoints
    externalDocs:
      url: http://docs.my-api.com/pet-operations.htm
  - name: Captures
    description: Capture endpoints
    externalDocs:
      url: http://docs.my-api.com/store-orders.htm
  - name: Simulate
    description: Simulate endpoint
    externalDocs:
      url: http://docs.my-api.com/store-orders.htm
paths:
  /token:
    post:
      description: Obtain a JWT for interacting with this API.
      summary: Obtain a bearer token.
      operationId: TokenPost
      responses:
        '200':
          description: A bearer token that can be used to make calls to other endpoints in this API.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: No credentials supplied
          content:
            application/json:
              schema: {}
        '401':
          description: Bad credentials
          content:
            application/json:
              schema: {}
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
        description: Token Request Credentials
        required: true
  /capture:
    get:
      description: Get a capture by its ID.
      summary: Get a capture.
      tags:
        - Captures
      operationId: AdminCaptureGet
      security:
        - Bearer: []
      parameters:
        - name: id
          in: query
          required: false
          description: Capture id
          schema:
            type: integer
      responses:
        '200':
          description: A capture object
          headers: {}
          content:
            application/json:
              schema:
                $ref: '../common.yaml#/components/schemas/Capture'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema: {}
    delete:
      description: Delete a capture
      summary: Delete a capture
      tags:
        - Captures
      operationId: AdminCaptureDelete
      security:
        - Bearer: []
      parameters:
        - name: id
          in: query
          required: false
          description: Capture id
          schema:
            type: integer
      responses:
        '204':
          description: Capture has been deleted
          content:
            application/json:
              schema: {}
        '400':
          description: bad input parameter
          content:
            application/json:
              schema: {}
        '404':
          description: No capture found
          content:
            application/json:
              schema: {}
  /captures:
    get:
      summary: Get a list of captures
      description: Get a list of captures ordered by ID.
      tags:
        - Captures
      operationId: CapturesGet
      parameters:
        - name: offset
          in: query
          description: Return captures starting from this index.
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit the number of captures returned.
          schema:
            type: integer
        - name: tag_id
          in: query
          description: Only returns captures from tag_id.
          schema:
            type: integer
      security:
        - Bearer: []
      responses:
        200:
          description: List of captures
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../common.yaml#/components/schemas/Capture'
        400:
          description: bad input parameter
          content:
            application/json:
              schema: {}
    post:
      description: Create a capture
      summary: Create a capture
      tags:
        - Captures
      operationId: AdminCapturePost
      security:
        - Bearer: []
      responses:
        '201':
          description: Capture created
          content:
            application/json:
              schema:
                $ref: '../common.yaml#/components/schemas/Capture'
          headers: {}
        '400':
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema: {}
        '409':
          description: a capture with the same id already exists
          content:
            application/json:
              schema: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CapturePost'
        description: Capture object
  /tag:
    get:
      description: Get a tag from an id.
      summary: Get a tag
      tags:
        - Tags
      operationId: TagGet
      security:
        - Bearer: []
      parameters:
        - name: id
          in: query
          required: false
          description: Tag id
          schema:
            type: integer
      responses:
        '200':
          description: A tag object
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminTag'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema: {}

    delete:
      description: Delete a tag
      summary: Delete a tag
      tags:
        - Tags
      operationId: TagDelete
      security:
        - Bearer: []
      parameters:
        - name: id
          in: query
          required: false
          description: Tag id
          schema:
            type: integer
      responses:
        '204':
          description: Tag has been deleted
          content:
            application/json:
              schema: {}
        '400':
          description: bad input parameter
          content:
            application/json:
              schema: {}
        '404':
          description: No tag found
          content:
            application/json:
              schema: {}
  /tags:
    get:
      description: Get a list of tags ordered by ID
      summary: Get a list of tags
      tags:
        - Tags
      operationId: TagsGet
      parameters:
        - name: offset
          in: query
          description: Return samples starting from this index.
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit the number of samples returned.
          schema:
            type: integer
      security:
        - Bearer: []
      responses:
        200:
          description: List of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdminTag'
        400:
          description: bad input parameter
          content:
            application/json:
              schema: {}
    post:
      description: Create a tag
      summary: Create a tag
      tags:
        - Tags
      operationId: TagPost
      security:
        - Bearer: []
      responses:
        201:
          description: Tag created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminTag'
          headers: {}
        400:
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminTag'
        description: Tag id
  /tag/{id}/simulate:
    get:
      summary: Get URL.
      description: Get URL from a simulated tag. This contains mock sensor data.
      tags:
        - Simulate
      operationId: TagSimGet
      security:
        - Bearer: []
      parameters:
        - name: id
          in: path
          required: true
          description: Tag id to simulate
          schema:
            type: integer
        - name: frontendurl
          in: query
          required: true
          description: URL of the consumer frontend application that will decode wscodec URLs.
          schema:
            type: string
        - name: nsamples
          in: query
          required: false
          description: Number of temperature and humidity samples to include in the wscodec URL.
            0 samples is valid and should raise an error.
          schema:
            type: integer
            default: 100
        - name: smplintervalmins
          in: query
          required: false
          description: Time interval between samples in minutes.
          schema:
            type: integer
            default: 10
        - name: format
          in: query
          required: false
          description: Format code e.g. 1 for temperature and humidity and 2 for temperarture samples only.
          schema:
            type: integer
            default: 1
        - name: usehmac
          in: query
          required: false
          description: Use HMAC rather than MD5.
          schema:
            type: boolean
            default: true
        - name: batvoltagemv
          in: query
          required: false
          description: Battery voltage in mV.
          schema:
            type: integer
            default: 3000
        - name: bor
          in: query
          required: false
          description: Reset caused by Brownout.
          schema:
            type: boolean
            default: false
        - name: svsh
          in: query
          required: false
          description: Reset caused by Supply Voltage Supervisor (High Side).
          schema:
            type: boolean
            default: false
        - name: wdt
          in: query
          required: false
          description: Reset caused by watchdog timer.
          schema:
            type: boolean
            default: false
        - name: misc
          in: query
          required: false
          description: Miscellaneous error flag on cupl Tag.
          schema:
            type: boolean
            default: false
        - name: lpm5wu
          in: query
          required: false
          description: Low Power Mode x.5 wakeup flag.
          schema:
            type: boolean
            default: false
        - name: clockfail
          in: query
          required: false
          description: Clock failure error flag.
          schema:
            type: boolean
            default: false
        - name: tagerror
          in: query
          required: false
          description: Initialise encoder with the error flag set. The circular buffer will be empty.
          schema:
            type: boolean
            default: false

      responses:
        '200':
          description: URL containing sensor data.
          headers: {}
          content:
            application/json:
              schema:
                type: string
        '400':
          description: bad input parameter
          content:
            application/json:
              schema: {}

components:
  schemas:
    AdminTag:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '../common.yaml#/components/schemas/Tag'
        - type: object
          properties:
            id:
              type: integer
              format: int32
            secretKey:
              example: AAAAcCcC
              type: string
    CapturePost:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '../common.yaml#/components/schemas/Capture'
        - type: object
          samples:
            type: array
            items:
              $ref: '../common.yaml#/components/schemas/CaptureSample'
    Token:
      title: Token
      type: object
      properties:
        token:
          example: eyJz93a...k4laUWw
          type: string
        token_type:
          example: Bearer
          type: string
    TokenRequest:
      title: TokenRequest
      type: object
      properties:
        client_id:
          example: ABE39cASE940
          type: string
        client_secret:
          example: nsfsaeASEFGSAE
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header