version: '3.1'
services:
 wsbackend:
  restart: 'no'
  build: .
  depends_on:
   - postgres
  environment:
   - ADMINAPI_CLIENTSECRET=dasgasesdave
   - TAGTOKEN_CLIENTSECRET=aelkfnaekflnas
   - DB_PASS=test_db_password
   - DB_USER=test_db_user
   - DB_NAME=test_db_name
   - DB_HOST=postgres
   - DB_PORT=5432
   - ADMINAPI_CLIENTSECRET=rakfnlsakenaslk
   - HASHIDS_SALT=salfkna04afksnl
   - CSRF_SESSION_KEY=aslfenalkse
   - SECRET_KEY=efasfsaeflksena
   - WSB_HOST=localhost
   - WSB_PORT=5001
   - SERVER_NAME=nginx
   - DROP_ON_INIT=True

 postgres:
  restart: 'no'
  image: postgres:latest
  environment: 
   - POSTGRES_PASSWORD=test_db_password
   - POSTGRES_USER=test_db_user
   - POSTGRES_DB=test_db_name

 nginx:
  restart: 'no'
  build: ./tests/nginx/
  ports:
   - 80:80
  depends_on:
   - wsbackend

 sut:
  restart: 'no'
  build: .
  depends_on:
   - nginx
  environment:
   - DB_PASS=test_db_password
   - ADMINAPI_CLIENTSECRET=rakfnlsakenaslk
   - CSRF_SESSION_KEY=aslfenalkse
   - SECRET_KEY=efasfsaeflksena
   - WSB_HOST=nginx
   - WSB_PORT=80
  command: bash -c "export PYTHONPATH="$PYTHONPATH:tests" && python3 -m pytest tests"
  
