version: '3.1'
services:
 wsbackend:
  restart: 'no'
  build: .
  links:
   - postgres:postgres
   - oauth-mock:oauth-mock

 postgres:
  restart: 'no'
  image: postgres:latest

 oauth-mock:
  restart: 'no'
  build: ./tests/oauth2-mock/