"""checking I am at the latest

Revision ID: 030257ba0fcb
Revises: 23d627f64a68
Create Date: 2018-11-03 12:49:11.205000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030257ba0fcb'
down_revision = '23d627f64a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
