"""added CaptureStatus table as a child of Capture

Revision ID: 0624fbb4585e
Revises: 442f630b750e
Create Date: 2019-01-14 19:05:14.811180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0624fbb4585e'
down_revision = '442f630b750e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=True),
    sa.Column('resetsalltime', sa.Integer(), nullable=True),
    sa.Column('brownout', sa.Boolean(), nullable=True),
    sa.Column('clockfail', sa.Boolean(), nullable=True),
    sa.Column('lpm5wakeup', sa.Boolean(), nullable=True),
    sa.Column('misc', sa.Boolean(), nullable=True),
    sa.Column('supervisor', sa.Boolean(), nullable=True),
    sa.Column('watchdog', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['capture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('capture', 'status')
    op.drop_column('capture', 'resetsalltime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capture', sa.Column('resetsalltime', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('capture', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('capture_status')
    # ### end Alembic commands ###
