"""modified boxviews

Revision ID: 1791bc648356
Revises: 330f68646851
Create Date: 2019-02-05 21:17:46.721873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1791bc648356'
down_revision = '330f68646851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
