"""made capturesample inside location not nullable

Revision ID: 23d627f64a68
Revises: 3f39d8161291
Create Date: 2018-10-26 21:10:29.407214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d627f64a68'
down_revision = '3f39d8161291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'capturesample_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'capturesample_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
