"""added timeregistered field to users table

Revision ID: 44eb49f3faa3
Revises: 53317cf688d1
Create Date: 2019-01-06 18:08:43.504352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44eb49f3faa3'
down_revision = '53317cf688d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timeregistered', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timeregistered')
    # ### end Alembic commands ###
