"""removed uneeded personal data from the users table

Revision ID: 53317cf688d1
Revises: 030257ba0fcb
Create Date: 2019-01-06 18:01:01.803843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53317cf688d1'
down_revision = '030257ba0fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'active')
    op.drop_column('user', 'locale')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'shortname')
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('shortname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('locale', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
