"""added logitem table

Revision ID: 544d755daa77
Revises: 6261a8c1da96
Create Date: 2018-10-08 23:46:04.436767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544d755daa77'
down_revision = '6261a8c1da96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_shortname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_shortname_key', 'user', ['shortname'])
    # ### end Alembic commands ###
