"""changed cascade settings on deletion of child items

Revision ID: 61c74af80357
Revises: 0624fbb4585e
Create Date: 2019-01-17 20:47:25.094413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c74af80357'
down_revision = '0624fbb4585e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
