"""test2

Revision ID: 6261a8c1da96
Revises: 1c6b830b3dfd
Create Date: 2018-10-06 00:13:29.169879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6261a8c1da96'
down_revision = '1c6b830b3dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('shortname', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('first_name', sa.String(length=50), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=50), server_default='', nullable=False),
    sa.Column('locale', sa.String(length=50), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_id'),
    sa.UniqueConstraint('shortname')
    )
    op.create_table('box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=8), nullable=True),
    sa.Column('secretkey', sa.String(length=8), nullable=True),
    sa.Column('timeregistered', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('batvoltage', sa.Float(), nullable=True),
    sa.Column('loopcount', sa.Integer(), nullable=True),
    sa.Column('cursorpos', sa.Integer(), nullable=True),
    sa.Column('scancount', sa.Integer(), nullable=True),
    sa.Column('timeint', sa.Integer(), nullable=True),
    sa.Column('md5', sa.String(length=20), nullable=True),
    sa.Column('smplcount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capture_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('timestampPosix', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('rh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['capture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capture_sample')
    op.drop_table('capture')
    op.drop_table('user_roles')
    op.drop_table('box')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
