"""added logitem table trying again

Revision ID: 82449d14a879
Revises: 544d755daa77
Create Date: 2018-10-08 23:47:20.002126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82449d14a879'
down_revision = '544d755daa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('eventname', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_logitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['logitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('view_logitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['logitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_logitem')
    op.drop_table('scan_logitem')
    op.drop_table('logitem')
    # ### end Alembic commands ###
