"""modified models

Revision ID: 8db1d7fca2ef
Revises: 61c74af80357
Create Date: 2019-01-27 16:50:41.017573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db1d7fca2ef'
down_revision = '61c74af80357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('box_user_id_fkey', 'box', type_='foreignkey')
    op.drop_column('box', 'user_id')
    op.add_column('capture', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'capture', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'capture', type_='foreignkey')
    op.drop_column('capture', 'user_id')
    op.add_column('box', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('box_user_id_fkey', 'box', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
