"""modified users table for flask_login to work

Revision ID: cc6bdd11cbe6
Revises: 9a107d99499a
Create Date: 2018-10-10 23:29:35.714861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6bdd11cbe6'
down_revision = '9a107d99499a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active', nullable=False, new_column_name='active')
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active', nullable=False, new_column_name='is_active')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
