"""boxserial is not appearing 2

Revision ID: cf0276bf4654
Revises: 8ef3b828f8e7
Create Date: 2019-02-07 21:01:59.576923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0276bf4654'
down_revision = '8ef3b828f8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('box_view', 'box_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('box_view', 'box_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
