"""test

Revision ID: e17399e0e301
Revises: 44eb49f3faa3
Create Date: 2019-01-06 18:23:08.396067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17399e0e301'
down_revision = '44eb49f3faa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
