openapi: 3.1.0
info:
  title: cupl Consumer API
  description: API endpoints that do not require token based authentication.
  contact:
    url: www.plotsensor.com
    email: malcolm@plotsensor.com
  version: 0.0.2
paths:
  /tag/{serial}:
    get:
      tags:
      - Tags
      summary: Get a tag by its serial.
      operationId: TagGet
      parameters:
      - name: serial
        required: True
        in: path
        description: Tag serial
        schema:
          type: string
      responses:
        200:
          description: A tag object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        400:
          description: Bad input parameter.
          content:
            application/json:
              schema:
                type: object
        404:
          description: Tag not found.
          content: {}
    put:
      tags:
        - Tags
      summary: Edit a tag description.
      operationId: TagDescriptionPut
      security:
        - TagToken: [ ]
      parameters:
        - name: serial
          required: True
          in: path
          description: Tag serial
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        200:
          description: A tag object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        400:
          description: Bad input parameter.
          content:
            application/json:
              schema:
                type: object
        401:
          description: Not authorised. TagToken is not valid for this tag.
          content:
            application/json:
              schema:
                type: object
        404:
          description: Tag not found.
          content: { }
  /tag/{serial}/samples:
    get:
      tags:
        - Tags
      summary: List unique samples
      operationId: UniqueSamplesGet
      parameters:
        - name: serial
          in: path
          description: Tag serial
          required: true
          schema:
            type: string
        - name: starttime
          in: query
          description: start timestamp as an ISO-8601 string.
          required: true
          schema:
            type: string
            format: datetime
        - name: endtime
          in: query
          description: end timestamp as an ISO-8601 string.
          required: true
          schema:
            type: string
            format: datetime
        - name: offset
          in: query
          description: Return samples starting from this index.
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit the number of samples returned.
          schema:
            type: integer
      responses:
        200:
          description: A list of samples from newest to oldest
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaptureSample'
        400:
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
  /tag/{serial}/captures:
    get:
      tags:
      - Tags
      summary: List captures
      operationId: CapturesGet
      parameters:
      - name: serial
        in: path
        description: Tag serial
        required: true
        schema:
          type: string
      - name: offset
        in: query
        description: Return samples starting from this index.
        schema:
          type: integer
      - name: limit
        in: query
        description: Limit the number of samples returned.
        schema:
          type: integer
      responses:
        200:
          description: A capture object
          headers:
            Link:
              schema:
                type: string
              description: |
                Links to related resources, in the format defined by
                [RFC 5988](https://tools.ietf.org/html/rfc5988#section-5).
                This will include a link with relation type `next` to the
                next page, if there is a next page.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Capture'
        400:
          description: invalid input, object invalid
          content:
            application/json:
              schema:
                type: object
        404:
          description: Tag with serial not found.
          content:
            application/json:
              schema:
                type: object
  /captures:
    post:
      tags:
        - Captures
      summary: Create a capture
      operationId: CapturesPost
      requestBody:
        description: Capture creation fields
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EncodedCapture'
        required: true
      responses:
        200:
          description: The newly created Capture with a TagToken.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaptureWithTagToken'
        400:
          description: invalid input, object invalid
          content:
            application/json:
              schema:
                type: object
        401:
          description: Not authorised. HMAC does not correspond to input data.
          content:
            application/json:
              schema:
                type: object
        404:
          description: Tag not found
          content:
            application/json:
              schema:
                type: object
        409:
          description: Conflict. A capture with this HMAC already exists. Dead battery
            or replay attack.
          content:
            application/json:
              schema:
                type: object
      x-codegen-request-body-name: body
  /capture/{id}:
    get:
      tags:
      - Captures
      summary: Get a capture by ID
      operationId: CaptureGet
      parameters:
        - name: id
          in: path
          description: Capture database ID
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A capture object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Capture'
        400:
          description: invalid input, object invalid
          content:
            application/json:
              schema:
                type: object
        404:
          description: Capture not found.
          content:
            application/json:
              schema:
                type: object
  /capture/{id}/samples:
    get:
      tags:
      - Captures
      summary: List samples.
      operationId: CaptureSamplesGet
      parameters:
      - name: id
        in: path
        required: True
        description: Capture database ID
        schema:
          type: integer
      - name: offset
        in: query
        description: Return samples starting from this index.
        schema:
          type: integer
      - name: limit
        in: query
        description: Limit the number of samples returned.
        schema:
          type: integer
      responses:
        200:
          description: A list of sample objects
          headers:
            Link:
              schema:
                type: string
              description: |
                Links to related resources, in the format defined by
                [RFC 5988](https://tools.ietf.org/html/rfc5988#section-5).
                This will include a link with relation type `next` to the
                next page, if there is a next page.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaptureSample'
        400:
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
  /tag/{serial}/webhook:
    get:
      tags:
      - Webhook
      summary: Get a webhook.
      operationId: WebhookGet
      security:
        - TagToken: [ ]
      parameters:
      - name: serial
        required: True
        in: path
        description: Tag serial
        schema:
          type: string
      responses:
        200:
          description: A webhook for this tag
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Webhook'
        400:
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
    post:
      tags:
        - Webhook
      summary: Post a webhook.
      operationId: WebhookPost
      security:
        - TagToken: [ ]
      requestBody:
        description: Webhook creation fields
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Webhook'
        required: true
      parameters:
        - name: serial
          required: True
          in: path
          description: Tag serial
          schema:
            type: string
      responses:
        200:
          description: A webhook for this tag
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Webhook'
        400:
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
        409:
          description: Conflict. This tag already has a webhook and only one is allowed.
          content:
            application/json:
              schema:
                type: object
    delete:
      description: Delete a webhook
      summary: Delete a webhook
      tags:
        - Webhook
      operationId: WebhookDelete
      security:
        - TagToken: [ ]
      parameters:
        - name: serial
          required: True
          in: path
          description: Tag serial
          schema:
            type: string
      responses:
        '204':
          description: Webhook has been deleted
          content:
            application/json:
              schema: { }
        '404':
          description: No tag found
          content:
            application/json:
              schema: { }

webhooks:
  captureDecoded:
    post:
      summary: Capture Decoded
      description: A capture has been read from a tag and decoded successfully.
      operationId: captureHook
      tags:
        - Webhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Webhook"
      responses:
        "200":
          description: Return a 200 status to indicate that the data was received successfully

components:
  schemas:
    Webhook:
      title: Webhook
      type: object
      properties:
        address:
          type: string
          description: URL to send the POST request to when the tag is scanned. Data are encoded as JSON.
          example: https://webhook.site/a1b658b6-6b23-4a49-959c-e9b33d20e034
        fields:
          type: string
          description: A string containing a comma separated list of fields to include in the capture webhook.
          example: samples, md5
        wh_secretkey:
          type: string
          description: The secret key used to create an HMAC-SHA256 signature in the webhook header.
          example: 4490vasnl456q2l
        created_on:
          type: string
          format: date-time
          readOnly: true
          example: 2019-01-15T13:09:52.456Z
    Tag:
      title: Tag
      type: object
      properties:
        description:
          type: string
          description: A free text field that a user can modify. It may be a description of the tag location.
                       Alternatively, this may be the URL of a linked frontend web application.
          example: In the kitchen.
        fwversion:
          type: string
          description: Version string for the cuplTag firmware.
          example: HT04_F1.1_C2
          readOnly: true
        hwversion:
          type: string
          description: Version string for the cuplTag hardware.
          example: HT04
          readOnly: true
        serial:
          type: string
          description: Serial of the tag that made the capture
          example: YWJjZGVM
          readOnly: true
        timeregistered:
          type: string
          description: Time the tag was created
          format: date-time
          example: 2019-01-15T13:09:52.456
          readOnly: true
    CaptureWithTagToken:
      allOf: # Combines the BasicErrorModel and the inline model
        - $ref: '#/components/schemas/Capture'
        - type: object
          properties:
            token:
              example: eyJz93a...k4laUWw
              type: string
            token_type:
              example: Bearer
              type: string
    Capture:
      title: Capture
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 232
          readOnly: true
        tagserial:
          type: string
          description: Serial of the tag that made the capture
          example: YWJjZGVM
          readOnly: true
        batvoltagemv:
          type: integer
          description: Tag battery voltage in mV.
          example: 3000
          readOnly: true
        cursorpos:
          type: integer
          description: Cursor position in the circular buffer.
          example: 20
          readOnly: true
        loopcount:
          type: integer
          description: Number of times the circularbuffer pointer has wrapped from
            the end to the beginning
          example: 2
          readOnly: true
        timeintmins:
          type: integer
          description: The time interval between samples in minutes.
          example: 12
          readOnly: true
        timestamp:
          type: string
          format: date-time
          example: 2019-01-15T13:09:52.456Z
          readOnly: true
        format:
          type: integer
          description: Indicates whether samples in this capture contain temperature and relative humidity readings
           or just temperature.
          example: 1
          readOnly: true
        status:
          $ref: '#/components/schemas/CaptureStatus'
    CaptureSample:
      title: CaptureSample
      required:
      - capture_id
      - id
      - temp
      - timestamp
      type: object
      properties:
        capture_id:
          type: integer
          description: ID of the parent Capture object
          format: int32
          example: 1
        id:
          type: integer
          description: CaptureSample ID
          format: int32
          example: 1
        rh:
          type: number
          description: Relative Humidity in percent
          format: double
          example: 55.0
        temp:
          type: number
          description: Temperature in degrees Celsius
          format: double
          example: 21.0
        timestamp:
          type: string
          description: Unix timestamp in seconds since January 1st 1970
          format: date-time
          example: 2019-01-15T13:09:52.456Z
    CaptureStatus:
      title: CaptureStatus
      type: object
      properties:
        id:
          type: integer
          description: CaptureStatus ID
          format: int32
          example: 1
        brownout:
          type: boolean
          description: True if the cause of the most recentreset was a brown out condition.
          example: false
          readOnly: true
        clockfail:
          type: boolean
          description: True if the most recent reset was caused by an MCU clock failure.
          example: false
          readOnly: true
        lpm5wakeup:
          type: boolean
          description: True if the MCU has woken up from LPM (Low Power Mode) x.5
          example: false
          readOnly: true
        misc:
          type: boolean
          description: True if a reset has occured for miscellaneous reasons
          example: false
          readOnly: true
        resetsalltime:
          type: integer
          example: 20
          readOnly: true
        supervisor:
          type: boolean
          description: True if the supply voltage supervisor caused the most recent
            reset
          example: false
          readOnly: true
        watchdog:
          type: boolean
          description: True if the MCU watchdog caused the most recent reset.
          example: false
          readOnly: true
    EncodedCapture:
      title: Base64 Encoded Capture
      type: object
      properties:
        serial:
          type: string
          description: Serial of the tag that made the capture
          example: YWJjZGVM
        circbufb64:
          type: string
          description: Circular buffer including samples encoded as base64.
          example: Add example here
        statusb64:
          type: string
          description: 12 character status string
          example: AAAAAAAA
        timeintb64:
          type: string
          description: Time interval in minutes in base64
          example: Awg=
        vfmtb64:
          type: string
          description: Version and Format encoded in base64. This may be zero padded so remove all but 4 last characters before use.
          example: "000000Ae3g"
  securitySchemes:
    TagToken: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
