name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd tests/oauth2-mock
    - run: npm install
    - run: npm install -g forever
    - run: forever start app.js
    - run: cd ../../

    - name: Install Python 3 dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: sudo apt-get install python3-setuptools

    - run: sudo apt-get install build-essential
    - run: sudo apt-get install python3-dev
    - run: sudo apt-get install libpq-dev
    - run: pip3 install -r requirements.txt


    - name: Start tests
      run:   python3 -m pytest
      env:
        CI: true
