name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ADMINAPI_CLIENTSECRET: "dasgasesdave"
      DB_PASS: "4tskngvknldkf"
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PORT: 5432

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd tests/oauth2-mock
    - run: npm install
    - run: npm install -g forever
    - run: forever start app.js
    - run: cd ../../

    - name: Install Python 3 dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: sudo apt-get install python3-setuptools

    - run: sudo apt-get install build-essential
    - run: sudo apt-get install python3-dev
    - run: sudo apt-get install libpq-dev
    - run: pip3 install -r requirements.txt

    - name: Install postgres
      uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
          postgresql db: ${{ env.DB_HOST }}
          postgresql user: ${{ env.DB_USER }}
          postgresql password: ${{ env.DB_PASS }}
    - name: Start tests
      run:   python3 -m pytest
      env:
        CI: true

